server:
  port: 8081
spring:
  cloud: 
    config:
      server:
        git: 
          default-label: gateway	
          uri: https://github.com/AnthonyCh23/microservicios-spring.git
          search-paths: config-data
  application:
    name: config-service